export const staticData = {
  iso_number: "01234567",
  policy_number: "GC-PCV-100930489",
  given_names: "Olivia",
  surname: "Ponton",
  email: "lecena@proton.me",
  mobile_number: "09162344333",
  amount: "1000",
  assured_name: "Olivia Ponton",
  agent_name: "Manuel",
  item_name: "Insurance Policy",
  item_quantity: "1",
  item_price: "1000",
  item_category: "Auto Insurance",
  fee_type: "Processing",
  fee_amount: "0",
};
